//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Praktika2012.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Phonenumber { get; set; }
        public int IdRole { get; set; }
        public string Address { get; set; }
        public double Salary { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public string SecretWord { get; set; }
        public Nullable<int> IdCleaningGroup { get; set; }
    
        public virtual CleaningGroup CleaningGroup { get; set; }
        public virtual Role Role { get; set; }
    }
}
