//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Praktika2012.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.OrderCleaningGroup = new HashSet<OrderCleaningGroup>();
            this.OrderConsumables = new HashSet<OrderConsumables>();
        }
    
        public int Id { get; set; }
        public int IdType { get; set; }
        public string Address { get; set; }
        public int RoomCount { get; set; }
        public double RoomSquare { get; set; }
        public System.DateTime Date { get; set; }
        public int IdCustomer { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual OrderType OrderType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderCleaningGroup> OrderCleaningGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderConsumables> OrderConsumables { get; set; }
    }
}
